### ISSUE TITLE
test报错

### ISSUE THREAD

**Issue by sunzhcas** [littlebeen/Diffusion-Enhancement-for-CR#9]
Total params: 36.80M
./pre_train
load model from ema_0.9999_010000.pt
Traceback (most recent call last):
  File "super_res_sample.py", line 175, in <module>
    sample()
  File "super_res_sample.py", line 76, in sample
    model.load_state_dict(
  File "/home/rog/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SuperResModel:

测试时候报错了，以上是错误，是不是某个包错了，请问你那里包都是什么版本的，谢谢

**Comment by dwtl995** [comment]
一样的问题
